import pandas as pd

diversityData = [
    {
        "key": 0,
        "property": "logP",
        "taskType": "regression",
        "number": "12682",
        "ratio": 5.837711617046118,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 1,
        "property": "logS",
        "taskType": "regression",
        "number": "4797",
        "ratio": 5.26592943654555,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 2,
        "property": "logD7.4",
        "taskType": "regression",
        "number": "19155",
        "ratio": 2.214348981399469,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 3,
        "property": "melting point",
        "taskType": "regression",
        "number": "9084",
        "ratio": 5.178663904712584,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 4,
        "property": "boiling point",
        "taskType": "regression",
        "number": "5758",
        "ratio": 11.72332942555686,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 5,
        "property": "pKa (acidic)",
        "taskType": "regression",
        "number": "2750",
        "ratio": 4.972650422675286,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 6,
        "property": "pKa (basic)",
        "taskType": "regression",
        "number": "2992",
        "ratio": 4.921259842519685,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 7,
        "property": "Human Intestinal Absorption",
        "taskType": "classification",
        "number": "1160 (1022/138)",
        "ratio": 1.5976993129892954,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 8,
        "property": "MDCK Permeability",
        "taskType": "regression",
        "number": "1140",
        "ratio": 1.71939477303989,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 9,
        "property": "P-glycoprotein inhibitor",
        "taskType": "classification",
        "number": "2209 (1315/894)",
        "ratio": 1.6889039013680125,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 10,
        "property": "P-glycoprotein substrate",
        "taskType": "classification",
        "number": "1185 (586/599)",
        "ratio": 1.27420998980632,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 11,
        "property": "Human Oral Bioavailability-20",
        "taskType": "classification",
        "number": "992 (753/239)",
        "ratio": 1.474056603773585,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 12,
        "property": "Human Oral Bioavailability-30",
        "taskType": "classification",
        "number": "992 (666/326)",
        "ratio": 1.474056603773585,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 13,
        "property": "Human Oral Bioavailability-50",
        "taskType": "classification",
        "number": "1475 (674/901)",
        "ratio": 1.5223017202009437,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 14,
        "property": "Caco-2 Permeability",
        "taskType": "regression",
        "number": "6502",
        "ratio": 1.8221574344023328,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 15,
        "property": "PAMPA",
        "taskType": "classification",
        "number": "2025 (1384/651)",
        "ratio": 1.460920379839299,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 16,
        "property": "BCRP inhibitor",
        "taskType": "classification",
        "number": "2799 (1701/1098)",
        "ratio": 1.720282126268708,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 17,
        "property": "OATP1B1 inhibitor",
        "taskType": "classification",
        "number": "2372 (1029/1343)",
        "ratio": 1.809299800977022,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 18,
        "property": "OATP1B3 inhibitor",
        "taskType": "classification",
        "number": "2228 (688/1540)",
        "ratio": 1.8040772145047808,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 19,
        "property": "BSEP inhibitor",
        "taskType": "classification",
        "number": "763 (288/475)",
        "ratio": 1.4903129657228018,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 20,
        "property": "MRP1 inhibitor",
        "taskType": "classification",
        "number": "1016 (379/636)",
        "ratio": 2.034174125305126,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 21,
        "property": "Blood_Brain Barrier Penetration",
        "taskType": "classification",
        "number": "2865 (1649/1216)",
        "ratio": 1.7543859649122808,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 22,
        "property": "Fraction unbound in plasms",
        "taskType": "regression",
        "number": "2575",
        "ratio": 1.550387596899225,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 23,
        "property": "Plasma protein binding",
        "taskType": "regression",
        "number": "4712",
        "ratio": 1.6661112962345883,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 24,
        "property": "Volume Distribution",
        "taskType": "regression",
        "number": "2440",
        "ratio": 1.7452006980802794,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 25,
        "property": "Clearance rate in Plasma",
        "taskType": "regression",
        "number": "831",
        "ratio": 1.440299582313121,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 26,
        "property": "half life",
        "taskType": "regression",
        "number": "3512",
        "ratio": 2.358490566037736,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 27,
        "property": "CYP1A2 inhibitor",
        "taskType": "classification",
        "number": "12635 (5876/6759)",
        "ratio": 1.665556295802798,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 28,
        "property": "CYP1A2 substrate",
        "taskType": "classification",
        "number": "366 (176/190)",
        "ratio": 1.4023278642546628,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 29,
        "property": "CYP2C19 inhibitor",
        "taskType": "classification",
        "number": "12611 (5770/6841)",
        "ratio": 1.665278934221482,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 30,
        "property": "CYP2C19 substrate",
        "taskType": "classification",
        "number": "258 (107/151)",
        "ratio": 1.4494854326714015,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 31,
        "property": "CYP2C9 inhibitor",
        "taskType": "classification",
        "number": "12111 (4017/8094)",
        "ratio": 1.684352366515075,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 32,
        "property": "CYP2C9 substrate",
        "taskType": "classification",
        "number": "811 (325/486)",
        "ratio": 1.5933715742511152,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 33,
        "property": "CYP2D6 inhibitor",
        "taskType": "classification",
        "number": "13073 (2535/10538)",
        "ratio": 1.6711229946524062,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 34,
        "property": "CYP2D6 substrate",
        "taskType": "classification",
        "number": "877 (435/442)",
        "ratio": 1.639344262295082,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 35,
        "property": "CYP3A4 inhibitor",
        "taskType": "classification",
        "number": "12339 (5092/7247)",
        "ratio": 1.6482610845557937,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 36,
        "property": "CYP3A4 substrate",
        "taskType": "classification",
        "number": "979 (497/482)",
        "ratio": 1.4721036360959812,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 37,
        "property": "CYP2B6 inhibitor",
        "taskType": "classification",
        "number": "521 (354/194)",
        "ratio": 1.5262515262515262,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 38,
        "property": "CYP2B6 substrate",
        "taskType": "classification",
        "number": "2860 (2600/260)",
        "ratio": 1.858390633711206,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 39,
        "property": "CYP2C8 inhibitor",
        "taskType": "classification",
        "number": "533 (221/312)",
        "ratio": 1.3292569453675396,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 40,
        "property": "Human Liver Microsomal Stability",
        "taskType": "classification",
        "number": "15521 (9450/6071)",
        "ratio": 1.885014137606032,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 41,
        "property": "AMES Mutagenicity",
        "taskType": "classification",
        "number": "7575 (4222/3353)",
        "ratio": 4.2105263157894735,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 42,
        "property": "Bioconcentration Factor",
        "taskType": "regression",
        "number": "676",
        "ratio": 4.198152812762385,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 43,
        "property": "Carcinogenicity",
        "taskType": "classification",
        "number": "1041 (516/525)",
        "ratio": 2.6896180742334588,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 44,
        "property": "Drug-induced liver injury",
        "taskType": "classification",
        "number": "467 (235/232)",
        "ratio": 1.5311590874291838,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 45,
        "property": "Eye Corrosion",
        "taskType": "classification",
        "number": "2298 (886/1412)",
        "ratio": 2.7129679869777537,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 46,
        "property": "Eye Irritation",
        "taskType": "classification",
        "number": "5219 (3874/1345)",
        "ratio": 4.452359750667855,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 47,
        "property": "FDA Maximum (Recommended) Daily Dose",
        "taskType": "classification",
        "number": "1197 (561/636)",
        "ratio": 1.8761726078799248,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 48,
        "property": "hERG inhibitor",
        "taskType": "classification",
        "number": "13845 (6922/6923)",
        "ratio": 1.3856172925038104,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 49,
        "property": "Human Hepatotoxicity",
        "taskType": "classification",
        "number": "2304 (1299/1005)",
        "ratio": 1.8611576400521124,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 50,
        "property": "IGC50",
        "taskType": "regression",
        "number": "1787",
        "ratio": 19.64636542239685,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 51,
        "property": "LC50DM",
        "taskType": "regression",
        "number": "347",
        "ratio": 3.943217665615142,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 52,
        "property": "LC50FM",
        "taskType": "regression",
        "number": "816",
        "ratio": 5.6657223796034,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 53,
        "property": "Drug-induced Neurotoxicity",
        "taskType": "classification",
        "number": "684 (329/355)",
        "ratio": 1.443001443001443,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 54,
        "property": "Ototoxicity",
        "taskType": "classification",
        "number": "2808 (1103/1705)",
        "ratio": 2.214348981399469,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 55,
        "property": "hERG inhibitor 10 um",
        "taskType": "classification",
        "number": "9076 (4786/5090)",
        "ratio": 1.8772292096865029,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 56,
        "property": "Hematotoxicity",
        "taskType": "classification",
        "number": "2329 (1624/765)",
        "ratio": 1.8604651162790695,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 57,
        "property": "Drug-induced Nephrotoxicity",
        "taskType": "classification",
        "number": "565 (278/287)",
        "ratio": 1.5566625155666252,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 58,
        "property": "Genotoxicity",
        "taskType": "classification",
        "number": "641 (377/264)",
        "ratio": 3.17359568390987,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 59,
        "property": "Immunitoxicity RPMI-8226",
        "taskType": "classification",
        "number": "48814 (3877/44937)",
        "ratio": 2.0593080724876445,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 60,
        "property": "A549 Cytotoxicity",
        "taskType": "classification",
        "number": "3302 (277/3025)",
        "ratio": 1.5487068297971194,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 61,
        "property": "Hek293 Cytotoxicity",
        "taskType": "classification",
        "number": "6900 (1455/5445)",
        "ratio": 3.4626038781163437,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 62,
        "property": "NR-AhR",
        "taskType": "classification",
        "number": "6603 (763/5840)",
        "ratio": 3.286230693394676,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 63,
        "property": "NR-AR",
        "taskType": "classification",
        "number": "7312 (266/7046)",
        "ratio": 3.2530904359141184,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 64,
        "property": "NR-AR-LBD",
        "taskType": "classification",
        "number": "6862 (233/6629)",
        "ratio": 3.370407819346141,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 65,
        "property": "NR-Aromatase",
        "taskType": "classification",
        "number": "5887 (256/5631)",
        "ratio": 3.3829499323410017,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 66,
        "property": "NR-ER",
        "taskType": "classification",
        "number": "6166 (669/5497)",
        "ratio": 3.356831151393085,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 67,
        "property": "NR-ER-LBD",
        "taskType": "classification",
        "number": "7052 (342/6710)",
        "ratio": 3.3200531208499333,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 68,
        "property": "NR-PPAR-gamma",
        "taskType": "classification",
        "number": "6586 (197/6389)",
        "ratio": 3.4518467380048325,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 69,
        "property": "Rat Oral Acute Toxicity",
        "taskType": "classification",
        "number": "7327 (2799/4528)",
        "ratio": 4.344048653344918,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 70,
        "property": "Respiratory Toxicity",
        "taskType": "classification",
        "number": "1388 (835/553)",
        "ratio": 2.3057412958266084,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 71,
        "property": "Skin Sensitization",
        "taskType": "classification",
        "number": "405 (274/131)",
        "ratio": 3.1397174254317117,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 72,
        "property": "SR-ARE",
        "taskType": "classification",
        "number": "5652 (865/4787)",
        "ratio": 3.558718861209964,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 73,
        "property": "SR-ATAD5",
        "taskType": "classification",
        "number": "7170 (249/6921)",
        "ratio": 3.3266799733865606,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 74,
        "property": "SR-HSE",
        "taskType": "classification",
        "number": "6319 (360/5959)",
        "ratio": 3.430531732418525,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 75,
        "property": "SR-MMP",
        "taskType": "classification",
        "number": "5913 (892/5021)",
        "ratio": 3.371544167228591,
        "grams": "",
        "distribution": "",
    },
    {
        "key": 76,
        "property": "SR-p53",
        "taskType": "classification",
        "number": "6915 (456/6459)",
        "ratio": 3.331112591605596,
        "grams": "",
        "distribution": "",
    },
]

publicationData = [
    {
        "title": "[1] Chemistry: chemical con artists foil drug discovery",
        "description": "Baell, J. and Walters, M.A.",
        "content": "Nature. 2014; 513, 481–483",
        "href": "/static/publication/img/e2.png",
        "cite": "Cite: 1092 times",
    }, {
        "title": "[2] The Ecstasy and Agony of Assay Interference Compounds",
        "description": "Aldrich, C., Bertozzi, C., Georg, G.I., Kiessling, L., Lindsley, C., Liotta, D., Merz, K.M., Jr., Schepartz, A. and Wang, S.",
        "content": "ACS Chem Neurosci. 2017; 8: 420-423.",
        "href": "/static/publication/img/nn1.jpg",
        "cite": "Cite: 75 times",
    }, {
        "title": "[3] Frequent hitters: nuisance artifacts in high-throughput screening",
        "description": "Yang, Z Y He, J H and Lu, A P et al.",
        "content": "Drug Discov. Today. 2020; 25: 657-667",
        "href": "/static/publication/img/e5.gif",
        "cite": "Cite: 37 times",
    }, {
        "title": "[4] Assay Guidance Manual",
        "description": "Markossian S, Grossman A, Brimacombe K, et al., editors.",
        "content": "Bethesda (MD): Eli Lilly & Company and the National Center for Advancing Translational Sciences; "
                   "2004-.Available from: https://www.ncbi.nlm.nih.gov/books/NBK53196/",
        "href": "/static/publication/img/11.png",
        "cite": "Cite: 62 times",
    }, {
        "title": "[5] New substructure filters for removal of pan assay interference compounds (PAINS) from screening libraries and for their exclusion in bioassays",
        "description": "Baell, J B and Holloway, G A.",
        "content": "J. Med. Chem. 2010; 53: 2719-2740",
        "href": "/static/publication/img/ee2.jpg",
        "cite": "Cite: 3518 times",
    }, {
        "title": "[6] Benchmarking the mechanisms of frequent hitters: limitation of PAINS alerts",
        "description": "Yang, Z. Y., Yang, Z. J., He, J. H., Lu, A. P., Liu, S., Hou, T. J., & Cao, D. S.",
        "content": "Drug Discovery Today. 2021; 26(6), 1353-1358",
        "href": "/static/publication/img/e6.gif",
        "cite": "Cite: 14 times",
    }, {
        "title": "[7] Computational advances in combating colloidal aggregation in drug discovery",
        "description": "Reker, D. et al.",
        "content": "Nat. Chem. 2019; 11, 402–418",
        "href": "/static/publication/img/e3.png",
        "cite": "Cite: 60 times",
    }, {
        "title": "[8] Structural Analysis and Identification of Colloidal Aggregators in Drug Discovery",
        "description": "Yang ZY, Dong J, Yang ZJ, et al.",
        "content": "J. Chem. Inf. Model. 2020;60(4): 2031-2043",
        "href": "/static/publication/img/e4.jpg",
        "cite": "Cite: 40 times",
    }, {
        "title": "[9] Structural Analysis and Identification of False Positive Hits in Luciferase-Based Assays",
        "description": "Yang, Z Y Yang, Z J and Dong, J et al.",
        "content": "J. Chem. Inf. 2020; Model. 59: 3714-3726",
        "href": "/static/publication/img/n8.jpg",
        "cite": "Cite: 17 times",
    }, {
        "title": "[10] ChemFLuo: a web-server for structure analysis and identification of fluorescent compounds",
        "description": "Yang, Z. Y., Dong, J., Yang, Z. J., Yin, M., Jiang, H. L., Lu, A. P., ... & Cao, D. S.",
        "content": "Briefings in Bioinformatics. 2021; 22(4), bbaa282",
        "href": "/static/publication/img/5.png",
        "cite": "Cite: 3 times",
    }, {
        "title": "[11] Rules for identifying potentially reactive or promiscuous compounds",
        "description": "Bruns, R.F. and Watson, I.A.",
        "content": "J. Med. Chem. 2012; 55, 9763–9772",
        "href": "/static/publication/img/ee3.jpg",
        "cite": "Cite: 305 times",
    }, {
        "title": "[12] A common mechanism underlying promiscuous inhibitors from virtual and high-throughput screening",
        "description": "McGovern, S.L., Caselli, E., Grigorieff, N. and Shoichet, B.K.",
        "content": "J. Med. Chem. 2002; 45, 1712-1722",
        "href": "/static/publication/img/ee1.jpg",
        "cite": "Cite: 1310 times",
    }, {
        "title": "[13] Application of Negative Design To Design a More Desirable Virtual Screening Library",
        "description": "Yang, Z.Y., He, J.H., Lu, A.P., Hou, T.J. and Cao, D.S.",
        "content": "J MED CHEM. 2020; 63, 4411-4429",
        "href": "/static/publication/img/e6.jpg",
        "cite": "Cite: 23 times",
    }, {
        "title": "[14] ALARM NMR: a rapid and robust experimental method to detect reactive false positives in "
                 "biochemical screens",
        "description": "Huth J R, Mendoza R, Olejniczak E T, et al.",
        "content": "J Am Chem Soc. 2005;127:217–24",
        "href": "/static/publication/img/n13.jpg",
        "cite": "Cite: 238 times",
    }]

webData = [{
    "title": "[1] ChemAgg",
    "href": "http://admet.scbdd.com/ChemAGG/index/",
    "img": "/static/publication/img/2.png",
    "description": "ChemAGG is a free webserver that could be used to easily filter out aggregators from potential "
                   "lead molecules!",
}, {
    "title": " [2] ChemFLuc",
    "href": "http://admet.scbdd.com/chemfluc/index/",
    "img": "/static/publication/img/2.png",
    "description": "ChemFLuc is a public webserver which could be useful to flag FLuc inhibitors in large dataset!",
}, {
    "title": " [3] ChemFLuo",
    "href": "http://admet.scbdd.com/chemfluo/index/",
    "img": "/static/publication/img/5.png",
    "description": "ChemFluo is a public webserver which could be useful to flag blue and green fluorescent compounds in large dataset!",
}, {
    "title": " [4] Scopy",
    "href": "https://github.com/kotori-y/Scopy",
    "img": "/static/publication/img/5.png",
    "description": "Scopy (Screnning COmpounds in PYthon), an integrated negative design python library designed for screening "
                   "out undesirable compounds in the early drug discovery. Scopy includes six modules, covering data preparation, "
                   "screening filters, the calculation of scaffolds and descriptors, and the visualization analysis."
}, {
    "title": " [5] Hit Dexter 3",
    "href": "https://nerdd.univie.ac.at/hitdexter3/",
    "img": "/static/publication/img/w5.png",
    "description": "Hit Dexter is a machine learning approach to estimate how likely a small molecule is to trigger a positive response in biochemical and biological assays. "
                   "The models were derived from a dataset of 250,000 compounds with experimentally determined activity for at least 100 different protein groups."
}, {
    "title": " [6] SCAM detective",
    "href": "https://scamdetective.mml.unc.edu/",
    "img": "/static/publication/img/w6.png",
    "description": "The SCAM Detective application provides an alternative method for assessing the potential of chemicals "
                   "to be putative aggregators and cause false-positive readouts in bioassays."
}]

if __name__ == "__main__":
    data = pd.DataFrame(diversityData)
    data['grams'] = data['property'].map(
        lambda x: '/static/diversity/scaffold/' + x + ".png")
    data['distribution'] = data['property'].map(
        lambda x: '/static/diversity/distribution/' + x + ".svg")
    print(data)
