# Generated by Django 4.1 on 2024-01-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemfh',
            name='aggregators_idx',
            field=models.TextField(blank=True, db_column='Aggregators_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='alarm',
            field=models.TextField(blank=True, db_column='ALARM_NMR_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='blue_idx',
            field=models.TextField(blank=True, db_column='Blue_fluorescence_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='bms',
            field=models.TextField(blank=True, db_column='BMS_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='chelator',
            field=models.TextField(blank=True, db_column='Chelator_Rule_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='fluc_idx',
            field=models.TextField(blank=True, db_column='Fluc_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='green_idx',
            field=models.TextField(blank=True, db_column='Green_fluorescence_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='gst',
            field=models.TextField(blank=True, db_column='GST_FHs_Rule_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='his',
            field=models.TextField(blank=True, db_column='His_FHs_Rule_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='luciferase',
            field=models.TextField(blank=True, db_column='Luciferase_Inhibitor_Rule_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='ntd',
            field=models.TextField(blank=True, db_column='NTD_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='other_idx',
            field=models.TextField(blank=True, db_column='Other_assay_interference_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='pains',
            field=models.TextField(blank=True, db_column='PAINS_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='potential',
            field=models.TextField(blank=True, db_column='Potential_Electrophilic_Rule_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='promiscuous_idx',
            field=models.TextField(blank=True, db_column='Promiscuous_index', null=True),
        ),
        migrations.AlterField(
            model_name='chemfh',
            name='reactive_idx',
            field=models.TextField(blank=True, db_column='Reactive_index', null=True),
        ),
    ]
