# Generated by Django 4.1 on 2024-01-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_chemfh_aggregators_idx_alter_chemfh_alarm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemfh',
            name='lilly',
            field=models.TextField(blank=True, db_column='Lilly_index', null=True),
        ),
    ]
