# Generated by Django 2.2 on 2020-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('authors', models.CharField(max_length=256)),
                ('publication', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('pub_date', models.CharField(max_length=32)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
