# Generated by Django 4.1 on 2024-01-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResearchResults',
        ),
    ]
